// Fallback sample data used ONLY when the backend at localhost:4000 (or your deployed backend URL) isn't reachable.
// Once the real backend responds, live data from the API is used instead automatically.
const FALLBACK_FLIGHTS = [
  {
    "id": "fl_del_bom",
    "country": "india",
    "from": "DEL",
    "fromCity": "Delhi",
    "to": "BOM",
    "toCity": "Mumbai",
    "basePrice": 6400,
    "currency": "INR",
    "airline": "IndiGo",
    "memberPrice": 3840.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_blr_hyd",
    "country": "india",
    "from": "BLR",
    "fromCity": "Bengaluru",
    "to": "HYD",
    "toCity": "Hyderabad",
    "basePrice": 4100,
    "currency": "INR",
    "airline": "Air India",
    "memberPrice": 2460.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_goi_del",
    "country": "india",
    "from": "GOI",
    "fromCity": "Goa",
    "to": "DEL",
    "toCity": "Delhi",
    "basePrice": 7900,
    "currency": "INR",
    "airline": "Vistara",
    "memberPrice": 4740.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_del_maa",
    "country": "india",
    "from": "DEL",
    "fromCity": "Delhi",
    "to": "MAA",
    "toCity": "Chennai",
    "basePrice": 6800,
    "currency": "INR",
    "airline": "IndiGo",
    "memberPrice": 4080.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_bom_ccu",
    "country": "india",
    "from": "BOM",
    "fromCity": "Mumbai",
    "to": "CCU",
    "toCity": "Kolkata",
    "basePrice": 7200,
    "currency": "INR",
    "airline": "Air India",
    "memberPrice": 4320.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_pnq_del",
    "country": "india",
    "from": "PNQ",
    "fromCity": "Pune",
    "to": "DEL",
    "toCity": "Delhi",
    "basePrice": 5900,
    "currency": "INR",
    "airline": "Vistara",
    "memberPrice": 3540.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_amd_bom",
    "country": "india",
    "from": "AMD",
    "fromCity": "Ahmedabad",
    "to": "BOM",
    "toCity": "Mumbai",
    "basePrice": 3800,
    "currency": "INR",
    "airline": "IndiGo",
    "memberPrice": 2280.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_cok_blr",
    "country": "india",
    "from": "COK",
    "fromCity": "Kochi",
    "to": "BLR",
    "toCity": "Bengaluru",
    "basePrice": 4300,
    "currency": "INR",
    "airline": "Air India Express",
    "memberPrice": 2580.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_ixc_del",
    "country": "india",
    "from": "IXC",
    "fromCity": "Chandigarh",
    "to": "DEL",
    "toCity": "Delhi",
    "basePrice": 3600,
    "currency": "INR",
    "airline": "IndiGo",
    "memberPrice": 2160.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_jai_bom",
    "country": "india",
    "from": "JAI",
    "fromCity": "Jaipur",
    "to": "BOM",
    "toCity": "Mumbai",
    "basePrice": 4900,
    "currency": "INR",
    "airline": "Vistara",
    "memberPrice": 2940.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_jfk_lax",
    "country": "usa",
    "from": "JFK",
    "fromCity": "New York",
    "to": "LAX",
    "toCity": "Los Angeles",
    "basePrice": 310,
    "currency": "USD",
    "airline": "Delta",
    "memberPrice": 186.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_ord_mia",
    "country": "usa",
    "from": "ORD",
    "fromCity": "Chicago",
    "to": "MIA",
    "toCity": "Miami",
    "basePrice": 225,
    "currency": "USD",
    "airline": "American Airlines",
    "memberPrice": 135.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_sfo_sea",
    "country": "usa",
    "from": "SFO",
    "fromCity": "San Francisco",
    "to": "SEA",
    "toCity": "Seattle",
    "basePrice": 190,
    "currency": "USD",
    "airline": "United",
    "memberPrice": 114.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_bos_dfw",
    "country": "usa",
    "from": "BOS",
    "fromCity": "Boston",
    "to": "DFW",
    "toCity": "Dallas",
    "basePrice": 265,
    "currency": "USD",
    "airline": "American Airlines",
    "memberPrice": 159.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_atl_den",
    "country": "usa",
    "from": "ATL",
    "fromCity": "Atlanta",
    "to": "DEN",
    "toCity": "Denver",
    "basePrice": 240,
    "currency": "USD",
    "airline": "Delta",
    "memberPrice": 144.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_las_jfk",
    "country": "usa",
    "from": "LAS",
    "fromCity": "Las Vegas",
    "to": "JFK",
    "toCity": "New York",
    "basePrice": 280,
    "currency": "USD",
    "airline": "JetBlue",
    "memberPrice": 168.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_iah_phx",
    "country": "usa",
    "from": "IAH",
    "fromCity": "Houston",
    "to": "PHX",
    "toCity": "Phoenix",
    "basePrice": 205,
    "currency": "USD",
    "airline": "United",
    "memberPrice": 123.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_yyz_yvr",
    "country": "canada",
    "from": "YYZ",
    "fromCity": "Toronto",
    "to": "YVR",
    "toCity": "Vancouver",
    "basePrice": 420,
    "currency": "CAD",
    "airline": "Air Canada",
    "memberPrice": 252.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_yul_yyc",
    "country": "canada",
    "from": "YUL",
    "fromCity": "Montreal",
    "to": "YYC",
    "toCity": "Calgary",
    "basePrice": 385,
    "currency": "CAD",
    "airline": "WestJet",
    "memberPrice": 231.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_yow_yyz",
    "country": "canada",
    "from": "YOW",
    "fromCity": "Ottawa",
    "to": "YYZ",
    "toCity": "Toronto",
    "basePrice": 210,
    "currency": "CAD",
    "airline": "Porter Airlines",
    "memberPrice": 126.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_yeg_yyz",
    "country": "canada",
    "from": "YEG",
    "fromCity": "Edmonton",
    "to": "YYZ",
    "toCity": "Toronto",
    "basePrice": 395,
    "currency": "CAD",
    "airline": "Air Canada",
    "memberPrice": 237.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_yhz_yul",
    "country": "canada",
    "from": "YHZ",
    "fromCity": "Halifax",
    "to": "YUL",
    "toCity": "Montreal",
    "basePrice": 310,
    "currency": "CAD",
    "airline": "WestJet",
    "memberPrice": 186.0,
    "discountPercent": 40.0
  },
  {
    "id": "fl_ywg_yyc",
    "country": "canada",
    "from": "YWG",
    "fromCity": "Winnipeg",
    "to": "YYC",
    "toCity": "Calgary",
    "basePrice": 275,
    "currency": "CAD",
    "airline": "Air Canada",
    "memberPrice": 165.0,
    "discountPercent": 40.0
  }
];

const FALLBACK_STAYS = [
  {
    "id": "st_goa_3bhk",
    "country": "india",
    "city": "Goa",
    "type": "Airbnb",
    "title": "3BHK Villa near Candolim Beach",
    "nights": 4,
    "standardPrice": 18200,
    "currency": "INR",
    "ourPrice": 10920.0,
    "savings": 7280.0,
    "savingsPercent": 40.0
  },
  {
    "id": "st_jaipur_haveli",
    "country": "india",
    "city": "Jaipur",
    "type": "Hotel",
    "title": "Heritage Haveli Room",
    "nights": 2,
    "standardPrice": 7600,
    "currency": "INR",
    "ourPrice": 4560.0,
    "savings": 3040.0,
    "savingsPercent": 40.0
  },
  {
    "id": "st_mumbai_hotel",
    "country": "india",
    "city": "Mumbai",
    "type": "Hotel",
    "title": "Business Hotel near BKC",
    "nights": 2,
    "standardPrice": 9800,
    "currency": "INR",
    "ourPrice": 5880.0,
    "savings": 3920.0,
    "savingsPercent": 40.0
  },
  {
    "id": "st_bengaluru_apt",
    "country": "india",
    "city": "Bengaluru",
    "type": "Airbnb",
    "title": "2BHK Apartment, Indiranagar",
    "nights": 3,
    "standardPrice": 10500,
    "currency": "INR",
    "ourPrice": 6300.0,
    "savings": 4200.0,
    "savingsPercent": 40.0
  },
  {
    "id": "st_udaipur_lake",
    "country": "india",
    "city": "Udaipur",
    "type": "Hotel",
    "title": "Lakeview Boutique Hotel",
    "nights": 2,
    "standardPrice": 12400,
    "currency": "INR",
    "ourPrice": 7440.0,
    "savings": 4960.0,
    "savingsPercent": 40.0
  },
  {
    "id": "st_delhi_hotel",
    "country": "india",
    "city": "Delhi",
    "type": "Hotel",
    "title": "4-Star Hotel, Connaught Place",
    "nights": 2,
    "standardPrice": 11200,
    "currency": "INR",
    "ourPrice": 6720.0,
    "savings": 4480.0,
    "savingsPercent": 40.0
  },
  {
    "id": "st_austin_loft",
    "country": "usa",
    "city": "Austin",
    "type": "Airbnb",
    "title": "1BR Downtown Loft",
    "nights": 3,
    "standardPrice": 412,
    "currency": "USD",
    "ourPrice": 247.2,
    "savings": 164.8,
    "savingsPercent": 40.0
  },
  {
    "id": "st_nyc_brooklyn",
    "country": "usa",
    "city": "Brooklyn",
    "type": "Airbnb",
    "title": "2BR Brownstone Apartment",
    "nights": 3,
    "standardPrice": 690,
    "currency": "USD",
    "ourPrice": 414.0,
    "savings": 276.0,
    "savingsPercent": 40.0
  },
  {
    "id": "st_miami_hotel",
    "country": "usa",
    "city": "Miami",
    "type": "Hotel",
    "title": "Beachfront Hotel Room",
    "nights": 3,
    "standardPrice": 585,
    "currency": "USD",
    "ourPrice": 351.0,
    "savings": 234.0,
    "savingsPercent": 40.0
  },
  {
    "id": "st_chicago_hotel",
    "country": "usa",
    "city": "Chicago",
    "type": "Hotel",
    "title": "Downtown Business Hotel",
    "nights": 2,
    "standardPrice": 398,
    "currency": "USD",
    "ourPrice": 238.8,
    "savings": 159.2,
    "savingsPercent": 40.0
  },
  {
    "id": "st_la_condo",
    "country": "usa",
    "city": "Los Angeles",
    "type": "Airbnb",
    "title": "Studio near Santa Monica",
    "nights": 3,
    "standardPrice": 465,
    "currency": "USD",
    "ourPrice": 279.0,
    "savings": 186.0,
    "savingsPercent": 40.0
  },
  {
    "id": "st_toronto_studio",
    "country": "canada",
    "city": "Toronto",
    "type": "Airbnb",
    "title": "Studio near Kensington Market",
    "nights": 2,
    "standardPrice": 298,
    "currency": "CAD",
    "ourPrice": 178.8,
    "savings": 119.2,
    "savingsPercent": 40.0
  },
  {
    "id": "st_vancouver_condo",
    "country": "canada",
    "city": "Vancouver",
    "type": "Airbnb",
    "title": "Waterfront Condo",
    "nights": 3,
    "standardPrice": 540,
    "currency": "CAD",
    "ourPrice": 324.0,
    "savings": 216.0,
    "savingsPercent": 40.0
  },
  {
    "id": "st_montreal_hotel",
    "country": "canada",
    "city": "Montreal",
    "type": "Hotel",
    "title": "Old Montreal Boutique Hotel",
    "nights": 2,
    "standardPrice": 356,
    "currency": "CAD",
    "ourPrice": 213.6,
    "savings": 142.4,
    "savingsPercent": 40.0
  },
  {
    "id": "st_calgary_hotel",
    "country": "canada",
    "city": "Calgary",
    "type": "Hotel",
    "title": "Downtown Calgary Hotel",
    "nights": 2,
    "standardPrice": 320,
    "currency": "CAD",
    "ourPrice": 192.0,
    "savings": 128.0,
    "savingsPercent": 40.0
  }
];

const FALLBACK_CARS = [
  {
    "id": "car_del_hatch",
    "country": "india",
    "city": "Delhi",
    "airport": "DEL",
    "category": "Hatchback",
    "company": "Budget Rentals",
    "standardDailyRate": 1400,
    "currency": "INR",
    "dailyRate": 840.0,
    "discountPercent": 40.0
  },
  {
    "id": "car_bom_suv",
    "country": "india",
    "city": "Mumbai",
    "airport": "BOM",
    "category": "SUV",
    "company": "Avis",
    "standardDailyRate": 2600,
    "currency": "INR",
    "dailyRate": 1560.0,
    "discountPercent": 40.0
  },
  {
    "id": "car_blr_sedan",
    "country": "india",
    "city": "Bengaluru",
    "airport": "BLR",
    "category": "Sedan",
    "company": "Enterprise",
    "standardDailyRate": 1900,
    "currency": "INR",
    "dailyRate": 1140.0,
    "discountPercent": 40.0
  },
  {
    "id": "car_goi_hatch",
    "country": "india",
    "city": "Goa",
    "airport": "GOI",
    "category": "Hatchback",
    "company": "Budget Rentals",
    "standardDailyRate": 1300,
    "currency": "INR",
    "dailyRate": 780.0,
    "discountPercent": 40.0
  },
  {
    "id": "car_hyd_suv",
    "country": "india",
    "city": "Hyderabad",
    "airport": "HYD",
    "category": "SUV",
    "company": "Avis",
    "currency": "INR",
    "standardDailyRate": 2400,
    "dailyRate": 1440.0,
    "discountPercent": 40.0
  },
  {
    "id": "car_maa_sedan",
    "country": "india",
    "city": "Chennai",
    "airport": "MAA",
    "category": "Sedan",
    "company": "Enterprise",
    "standardDailyRate": 1850,
    "currency": "INR",
    "dailyRate": 1110.0,
    "discountPercent": 40.0
  },
  {
    "id": "car_lax_sedan",
    "country": "usa",
    "city": "Los Angeles",
    "airport": "LAX",
    "category": "Sedan",
    "company": "Enterprise",
    "standardDailyRate": 58,
    "currency": "USD",
    "dailyRate": 34.8,
    "discountPercent": 40.0
  },
  {
    "id": "car_mia_coupe",
    "country": "usa",
    "city": "Miami",
    "airport": "MIA",
    "category": "Coupe",
    "company": "Avis",
    "standardDailyRate": 89,
    "currency": "USD",
    "dailyRate": 53.4,
    "discountPercent": 40.0
  },
  {
    "id": "car_ord_suv",
    "country": "usa",
    "city": "Chicago",
    "airport": "ORD",
    "category": "SUV",
    "company": "Budget Rentals",
    "standardDailyRate": 76,
    "currency": "USD",
    "dailyRate": 45.6,
    "discountPercent": 40.0
  },
  {
    "id": "car_jfk_compact",
    "country": "usa",
    "city": "New York",
    "airport": "JFK",
    "category": "Compact",
    "company": "Enterprise",
    "standardDailyRate": 64,
    "currency": "USD",
    "dailyRate": 38.4,
    "discountPercent": 40.0
  },
  {
    "id": "car_dfw_suv",
    "country": "usa",
    "city": "Dallas",
    "airport": "DFW",
    "category": "SUV",
    "company": "Avis",
    "standardDailyRate": 71,
    "currency": "USD",
    "dailyRate": 42.6,
    "discountPercent": 40.0
  },
  {
    "id": "car_yyz_suv",
    "country": "canada",
    "city": "Toronto",
    "airport": "YYZ",
    "category": "SUV",
    "company": "Avis",
    "standardDailyRate": 74,
    "currency": "CAD",
    "dailyRate": 44.4,
    "discountPercent": 40.0
  },
  {
    "id": "car_yvr_compact",
    "country": "canada",
    "city": "Vancouver",
    "airport": "YVR",
    "category": "Compact",
    "company": "Budget Rentals",
    "standardDailyRate": 52,
    "currency": "CAD",
    "dailyRate": 31.2,
    "discountPercent": 40.0
  },
  {
    "id": "car_yul_sedan",
    "country": "canada",
    "city": "Montreal",
    "airport": "YUL",
    "category": "Sedan",
    "company": "Enterprise",
    "standardDailyRate": 60,
    "currency": "CAD",
    "dailyRate": 36.0,
    "discountPercent": 40.0
  },
  {
    "id": "car_yyc_hatch",
    "country": "canada",
    "city": "Calgary",
    "airport": "YYC",
    "category": "Hatchback",
    "company": "Budget Rentals",
    "standardDailyRate": 49,
    "currency": "CAD",
    "dailyRate": 29.4,
    "discountPercent": 40.0
  }
];
